
version: 2

models:
    - name: modelo1
      description: "A starter dbt model"
      columns:
          - name: player_id
            description: "The primary key for this table"
          - name: team_id
          - name: name
          - name: positon
          - name: date_of_birth
          - name: nationality
            tests:
                - unique
                - not_null

    - name: modelo2
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
