version: 2

sources:
  - name: raw_data                # alias a tu elección
    database: "grounded-burner-459901-g3"
    schema:   "dbt_test_zero_to_hero"

    tables:
      - name: coaches
      - name: leagues
      - name: scores
      - name: matches
      - name: players
      - name: seasons
      - name: stadiums
      - name: standings
      - name: teams


      


